// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: core.proto

package proto

import (
	context "context"
	errors "errors"
	drpc1 "github.com/planetscale/vtprotobuf/codec/drpc"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_core_proto struct{}

func (drpcEncoding_File_core_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return drpc1.Marshal(msg)
}

func (drpcEncoding_File_core_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.Unmarshal(buf, msg)
}

func (drpcEncoding_File_core_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return drpc1.JSONMarshal(msg)
}

func (drpcEncoding_File_core_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return drpc1.JSONUnmarshal(buf, msg)
}

type DRPCFlowDBClient interface {
	DRPCConn() drpc.Conn

	CreateTable(ctx context.Context, in *CreateTableRequest) (*CreateTableResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest) (*DropTableResponse, error)
	Insert(ctx context.Context, in *InsertRequest) (*InsertResponse, error)
	Delete(ctx context.Context, in *DeleteRequest) (*DeleteResponse, error)
	Query(ctx context.Context, in *QueryRequest) (*QueryResponse, error)
	StreamQuery(ctx context.Context, in *QueryRequest) (DRPCFlowDB_StreamQueryClient, error)
	GetTable(ctx context.Context, in *GetTableRequest) (*GetTableResponse, error)
	ListTables(ctx context.Context, in *Empty) (*ListTablesResponse, error)
	Backup(ctx context.Context, in *BackupRequest) (DRPCFlowDB_BackupClient, error)
	BackupToS3(ctx context.Context, in *S3BackupRequest) (DRPCFlowDB_BackupToS3Client, error)
	RestoreFromS3(ctx context.Context, in *S3RestoreRequest) (DRPCFlowDB_RestoreFromS3Client, error)
	GetStats(ctx context.Context, in *Empty) (*DBStats, error)
}

type drpcFlowDBClient struct {
	cc drpc.Conn
}

func NewDRPCFlowDBClient(cc drpc.Conn) DRPCFlowDBClient {
	return &drpcFlowDBClient{cc}
}

func (c *drpcFlowDBClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcFlowDBClient) CreateTable(ctx context.Context, in *CreateTableRequest) (*CreateTableResponse, error) {
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/CreateTable", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) DropTable(ctx context.Context, in *DropTableRequest) (*DropTableResponse, error) {
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/DropTable", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) Insert(ctx context.Context, in *InsertRequest) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/Insert", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) Delete(ctx context.Context, in *DeleteRequest) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/Delete", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) Query(ctx context.Context, in *QueryRequest) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/Query", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) StreamQuery(ctx context.Context, in *QueryRequest) (DRPCFlowDB_StreamQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, "/flowdb.FlowDB/StreamQuery", drpcEncoding_File_core_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcFlowDB_StreamQueryClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCFlowDB_StreamQueryClient interface {
	drpc.Stream
	Recv() (*StreamQueryChunk, error)
}

type drpcFlowDB_StreamQueryClient struct {
	drpc.Stream
}

func (x *drpcFlowDB_StreamQueryClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcFlowDB_StreamQueryClient) Recv() (*StreamQueryChunk, error) {
	m := new(StreamQueryChunk)
	if err := x.MsgRecv(m, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcFlowDB_StreamQueryClient) RecvMsg(m *StreamQueryChunk) error {
	return x.MsgRecv(m, drpcEncoding_File_core_proto{})
}

func (c *drpcFlowDBClient) GetTable(ctx context.Context, in *GetTableRequest) (*GetTableResponse, error) {
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/GetTable", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) ListTables(ctx context.Context, in *Empty) (*ListTablesResponse, error) {
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/ListTables", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcFlowDBClient) Backup(ctx context.Context, in *BackupRequest) (DRPCFlowDB_BackupClient, error) {
	stream, err := c.cc.NewStream(ctx, "/flowdb.FlowDB/Backup", drpcEncoding_File_core_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcFlowDB_BackupClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCFlowDB_BackupClient interface {
	drpc.Stream
	Recv() (*BackupChunk, error)
}

type drpcFlowDB_BackupClient struct {
	drpc.Stream
}

func (x *drpcFlowDB_BackupClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcFlowDB_BackupClient) Recv() (*BackupChunk, error) {
	m := new(BackupChunk)
	if err := x.MsgRecv(m, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcFlowDB_BackupClient) RecvMsg(m *BackupChunk) error {
	return x.MsgRecv(m, drpcEncoding_File_core_proto{})
}

func (c *drpcFlowDBClient) BackupToS3(ctx context.Context, in *S3BackupRequest) (DRPCFlowDB_BackupToS3Client, error) {
	stream, err := c.cc.NewStream(ctx, "/flowdb.FlowDB/BackupToS3", drpcEncoding_File_core_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcFlowDB_BackupToS3Client{stream}
	if err := x.MsgSend(in, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCFlowDB_BackupToS3Client interface {
	drpc.Stream
	Recv() (*S3BackupChunk, error)
}

type drpcFlowDB_BackupToS3Client struct {
	drpc.Stream
}

func (x *drpcFlowDB_BackupToS3Client) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcFlowDB_BackupToS3Client) Recv() (*S3BackupChunk, error) {
	m := new(S3BackupChunk)
	if err := x.MsgRecv(m, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcFlowDB_BackupToS3Client) RecvMsg(m *S3BackupChunk) error {
	return x.MsgRecv(m, drpcEncoding_File_core_proto{})
}

func (c *drpcFlowDBClient) RestoreFromS3(ctx context.Context, in *S3RestoreRequest) (DRPCFlowDB_RestoreFromS3Client, error) {
	stream, err := c.cc.NewStream(ctx, "/flowdb.FlowDB/RestoreFromS3", drpcEncoding_File_core_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcFlowDB_RestoreFromS3Client{stream}
	if err := x.MsgSend(in, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCFlowDB_RestoreFromS3Client interface {
	drpc.Stream
	Recv() (*S3RestoreChunk, error)
}

type drpcFlowDB_RestoreFromS3Client struct {
	drpc.Stream
}

func (x *drpcFlowDB_RestoreFromS3Client) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcFlowDB_RestoreFromS3Client) Recv() (*S3RestoreChunk, error) {
	m := new(S3RestoreChunk)
	if err := x.MsgRecv(m, drpcEncoding_File_core_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcFlowDB_RestoreFromS3Client) RecvMsg(m *S3RestoreChunk) error {
	return x.MsgRecv(m, drpcEncoding_File_core_proto{})
}

func (c *drpcFlowDBClient) GetStats(ctx context.Context, in *Empty) (*DBStats, error) {
	out := new(DBStats)
	err := c.cc.Invoke(ctx, "/flowdb.FlowDB/GetStats", drpcEncoding_File_core_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCFlowDBServer interface {
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	StreamQuery(*QueryRequest, DRPCFlowDB_StreamQueryStream) error
	GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error)
	ListTables(context.Context, *Empty) (*ListTablesResponse, error)
	Backup(*BackupRequest, DRPCFlowDB_BackupStream) error
	BackupToS3(*S3BackupRequest, DRPCFlowDB_BackupToS3Stream) error
	RestoreFromS3(*S3RestoreRequest, DRPCFlowDB_RestoreFromS3Stream) error
	GetStats(context.Context, *Empty) (*DBStats, error)
}

type DRPCFlowDBUnimplementedServer struct{}

func (s *DRPCFlowDBUnimplementedServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) StreamQuery(*QueryRequest, DRPCFlowDB_StreamQueryStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) ListTables(context.Context, *Empty) (*ListTablesResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) Backup(*BackupRequest, DRPCFlowDB_BackupStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) BackupToS3(*S3BackupRequest, DRPCFlowDB_BackupToS3Stream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) RestoreFromS3(*S3RestoreRequest, DRPCFlowDB_RestoreFromS3Stream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCFlowDBUnimplementedServer) GetStats(context.Context, *Empty) (*DBStats, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCFlowDBDescription struct{}

func (DRPCFlowDBDescription) NumMethods() int { return 12 }

func (DRPCFlowDBDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/flowdb.FlowDB/CreateTable", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					CreateTable(
						ctx,
						in1.(*CreateTableRequest),
					)
			}, DRPCFlowDBServer.CreateTable, true
	case 1:
		return "/flowdb.FlowDB/DropTable", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					DropTable(
						ctx,
						in1.(*DropTableRequest),
					)
			}, DRPCFlowDBServer.DropTable, true
	case 2:
		return "/flowdb.FlowDB/Insert", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					Insert(
						ctx,
						in1.(*InsertRequest),
					)
			}, DRPCFlowDBServer.Insert, true
	case 3:
		return "/flowdb.FlowDB/Delete", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					Delete(
						ctx,
						in1.(*DeleteRequest),
					)
			}, DRPCFlowDBServer.Delete, true
	case 4:
		return "/flowdb.FlowDB/Query", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					Query(
						ctx,
						in1.(*QueryRequest),
					)
			}, DRPCFlowDBServer.Query, true
	case 5:
		return "/flowdb.FlowDB/StreamQuery", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCFlowDBServer).
					StreamQuery(
						in1.(*QueryRequest),
						&drpcFlowDB_StreamQueryStream{in2.(drpc.Stream)},
					)
			}, DRPCFlowDBServer.StreamQuery, true
	case 6:
		return "/flowdb.FlowDB/GetTable", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					GetTable(
						ctx,
						in1.(*GetTableRequest),
					)
			}, DRPCFlowDBServer.GetTable, true
	case 7:
		return "/flowdb.FlowDB/ListTables", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					ListTables(
						ctx,
						in1.(*Empty),
					)
			}, DRPCFlowDBServer.ListTables, true
	case 8:
		return "/flowdb.FlowDB/Backup", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCFlowDBServer).
					Backup(
						in1.(*BackupRequest),
						&drpcFlowDB_BackupStream{in2.(drpc.Stream)},
					)
			}, DRPCFlowDBServer.Backup, true
	case 9:
		return "/flowdb.FlowDB/BackupToS3", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCFlowDBServer).
					BackupToS3(
						in1.(*S3BackupRequest),
						&drpcFlowDB_BackupToS3Stream{in2.(drpc.Stream)},
					)
			}, DRPCFlowDBServer.BackupToS3, true
	case 10:
		return "/flowdb.FlowDB/RestoreFromS3", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCFlowDBServer).
					RestoreFromS3(
						in1.(*S3RestoreRequest),
						&drpcFlowDB_RestoreFromS3Stream{in2.(drpc.Stream)},
					)
			}, DRPCFlowDBServer.RestoreFromS3, true
	case 11:
		return "/flowdb.FlowDB/GetStats", drpcEncoding_File_core_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCFlowDBServer).
					GetStats(
						ctx,
						in1.(*Empty),
					)
			}, DRPCFlowDBServer.GetStats, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterFlowDB(mux drpc.Mux, impl DRPCFlowDBServer) error {
	return mux.Register(impl, DRPCFlowDBDescription{})
}

type DRPCFlowDB_CreateTableStream interface {
	drpc.Stream
	SendAndClose(*CreateTableResponse) error
}

type drpcFlowDB_CreateTableStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_CreateTableStream) SendAndClose(m *CreateTableResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_DropTableStream interface {
	drpc.Stream
	SendAndClose(*DropTableResponse) error
}

type drpcFlowDB_DropTableStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_DropTableStream) SendAndClose(m *DropTableResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_InsertStream interface {
	drpc.Stream
	SendAndClose(*InsertResponse) error
}

type drpcFlowDB_InsertStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_InsertStream) SendAndClose(m *InsertResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_DeleteStream interface {
	drpc.Stream
	SendAndClose(*DeleteResponse) error
}

type drpcFlowDB_DeleteStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_DeleteStream) SendAndClose(m *DeleteResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_QueryStream interface {
	drpc.Stream
	SendAndClose(*QueryResponse) error
}

type drpcFlowDB_QueryStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_QueryStream) SendAndClose(m *QueryResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_StreamQueryStream interface {
	drpc.Stream
	Send(*StreamQueryChunk) error
}

type drpcFlowDB_StreamQueryStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_StreamQueryStream) Send(m *StreamQueryChunk) error {
	return x.MsgSend(m, drpcEncoding_File_core_proto{})
}

type DRPCFlowDB_GetTableStream interface {
	drpc.Stream
	SendAndClose(*GetTableResponse) error
}

type drpcFlowDB_GetTableStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_GetTableStream) SendAndClose(m *GetTableResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_ListTablesStream interface {
	drpc.Stream
	SendAndClose(*ListTablesResponse) error
}

type drpcFlowDB_ListTablesStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_ListTablesStream) SendAndClose(m *ListTablesResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCFlowDB_BackupStream interface {
	drpc.Stream
	Send(*BackupChunk) error
}

type drpcFlowDB_BackupStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_BackupStream) Send(m *BackupChunk) error {
	return x.MsgSend(m, drpcEncoding_File_core_proto{})
}

type DRPCFlowDB_BackupToS3Stream interface {
	drpc.Stream
	Send(*S3BackupChunk) error
}

type drpcFlowDB_BackupToS3Stream struct {
	drpc.Stream
}

func (x *drpcFlowDB_BackupToS3Stream) Send(m *S3BackupChunk) error {
	return x.MsgSend(m, drpcEncoding_File_core_proto{})
}

type DRPCFlowDB_RestoreFromS3Stream interface {
	drpc.Stream
	Send(*S3RestoreChunk) error
}

type drpcFlowDB_RestoreFromS3Stream struct {
	drpc.Stream
}

func (x *drpcFlowDB_RestoreFromS3Stream) Send(m *S3RestoreChunk) error {
	return x.MsgSend(m, drpcEncoding_File_core_proto{})
}

type DRPCFlowDB_GetStatsStream interface {
	drpc.Stream
	SendAndClose(*DBStats) error
}

type drpcFlowDB_GetStatsStream struct {
	drpc.Stream
}

func (x *drpcFlowDB_GetStatsStream) SendAndClose(m *DBStats) error {
	if err := x.MsgSend(m, drpcEncoding_File_core_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
